### ISSUE TITLE
Margins aren't being applied. What am I doing wrong?

### ISSUE THREAD

**Issue by damirkotoric** [hrescak/Sketch-Flex-Layout#9]
Love your plugin! But I can't seem to get margins to work properly. Here is my Sketch file: https://dl.dropboxusercontent.com/u/6258503/sketch-flex-layout-help.sketch Can you please take a look and tell me if I'm doing something wrong or if this is a bug with your plugin?

<img width="1552" alt="screen shot 2015-07-24 at 12 08 44 pm" src="https://cloud.githubusercontent.com/assets/520622/8872387/c4e3cc7a-31fc-11e5-87b7-735dd2d46315.png">

Many thanks,
Damir

**Comment by hrescak** [comment]
The problem is the caption was inside of the photo object, causing it to overlap. It also had two bg layers, where one of them is being ignored
<img width="1449" alt="screen shot 2015-07-30 at 9 50 53 pm" src="https://cloud.githubusercontent.com/assets/753458/9000956/15e09cea-3705-11e5-8242-f1284116103a.png">

Here's the source file: https://www.dropbox.com/s/dda8p0ar864igh9/sketch-flex-layout-help.sketch?dl=0

**Comment by damirkotoric** [comment]
Thank you.
